
import javax.swing.JOptionPane;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class NewJFrame extends javax.swing.JFrame {
    private int id=0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblName = new javax.swing.JLabel();
        jlblAdd = new javax.swing.JLabel();
        jlblClass = new javax.swing.JLabel();
        jlblMarks = new javax.swing.JLabel();
        jlblSem1 = new javax.swing.JLabel();
        jlblSem2 = new javax.swing.JLabel();
        lblSemj3 = new javax.swing.JLabel();
        jbtnSubmit = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jtxtName = new javax.swing.JTextField();
        jtxtClass = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaAdd = new javax.swing.JTextArea();
        jtxtSem1 = new javax.swing.JTextField();
        jtxtSem2 = new javax.swing.JTextField();
        jtxtSem3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblName.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jlblName.setText("Name");

        jlblAdd.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jlblAdd.setText("Address");

        jlblClass.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jlblClass.setText("Class");

        jlblMarks.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jlblMarks.setText("Marks");

        jlblSem1.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jlblSem1.setText("SEM I");

        jlblSem2.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jlblSem2.setText("SEM II");

        lblSemj3.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lblSemj3.setText("SEM III");

        jbtnSubmit.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jbtnSubmit.setText("Submit");
        jbtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubmitActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jtxtName.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jtxtClass.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jtxtClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtClassActionPerformed(evt);
            }
        });

        jtxtAreaAdd.setColumns(20);
        jtxtAreaAdd.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jtxtAreaAdd.setLineWrap(true);
        jtxtAreaAdd.setRows(5);
        jtxtAreaAdd.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jtxtAreaAdd);

        jtxtSem1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jtxtSem2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jtxtSem3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 51));
        jLabel8.setText("(In Number)");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("/ 700");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setText("/ 700");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setText("/ 700");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblClass, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(154, 154, 154)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtClass, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlblName, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jbtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jlblMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblSem1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSemj3)
                            .addComponent(jlblSem2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtSem1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtSem3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtSem2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jlblName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jlblAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblClass)
                    .addComponent(jtxtClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jlblMarks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlblSem1)
                                    .addComponent(jtxtSem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtSem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblSem2)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSemj3)
                            .addComponent(jtxtSem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtClassActionPerformed

    private void jbtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubmitActionPerformed
        // TODO add your handling code here:
        if((jtxtName.getText()).equals("") || jtxtClass.getText().equals("") || jtxtSem1.getText().equals("") || jtxtSem2.getText().equals("") || jtxtSem3.getText().equals("") || jtxtAreaAdd.getText().equals("")){
        JOptionPane.showMessageDialog(this,"Please fill all the details");
        }
        else{
            try{
              int mark1=Integer.parseInt(jtxtSem1.getText());
              int mark2=Integer.parseInt(jtxtSem2.getText());
              int mark3=Integer.parseInt(jtxtSem3.getText());
              float sum=mark1+mark2+mark3;
              float per=(sum/2100)*100;
              String name=jtxtName.getText();
              String add=jtxtAreaAdd.getText();
              String clas=jtxtClass.getText();
              if (mark1<=700 && mark2<=700 && mark3<=700){
              String msg="Details : ";
              msg+="\nName : "+jtxtName.getText();
              msg+="\nAddress : "+jtxtAreaAdd.getText();
              msg+="\nClass : "+jtxtClass.getText();
              msg+="\nMarks : ";
              msg+="\nSem I : "+jtxtSem1.getText();
              msg+="\nSem II : "+jtxtSem2.getText();
              msg+="\nSem III : "+jtxtSem3.getText();
              msg+="\nTotal : "+sum;
              msg+="\nPercentage : "+per;
              msg+="\n\n";
              msg+="-------Record submitted------";
              JOptionPane.showMessageDialog(this,msg);
              try{
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/java","root","root");
            System.out.println("Connection created");
            String s="insert into Form(id,name,address,class,semI,semII,semIII,total,percentage) values(?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps=con.prepareStatement(s);
            id=id+1;
            ps.setInt(1,id);
            ps.setString(2,name);
            ps.setString(3,add);
            ps.setString(4,clas);
            ps.setInt(5,mark1);
            ps.setInt(6,mark2);
            ps.setInt(7,mark3);
            ps.setFloat(8,sum);
            ps.setFloat(9,per);
            
            
            ps.execute();
            con.close();
            System.out.println("Records inserted");
            
            //Exception to particularly catch SQL operations
        }catch(Exception e){
            System.out.println("Exception"+e);
        }}
              else{
                  JOptionPane.showMessageDialog(this,"Please enter semester marks smaller than or equal to 700");
                  jtxtSem1.setText("");
                  jtxtSem2.setText("");
                  jtxtSem3.setText("");
              }
              //Exception to catch  invalid marks only
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Please enter marks in number");
            }
        }
    }//GEN-LAST:event_jbtnSubmitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        jtxtName.setText("");
        jtxtAreaAdd.setText("");
        jtxtClass.setText("");
        jtxtSem1.setText("");
        jtxtSem2.setText("");
        jtxtSem3.setText("");
      
    }//GEN-LAST:event_jbtnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSubmit;
    private javax.swing.JLabel jlblAdd;
    private javax.swing.JLabel jlblClass;
    private javax.swing.JLabel jlblMarks;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblSem1;
    private javax.swing.JLabel jlblSem2;
    private javax.swing.JTextArea jtxtAreaAdd;
    private javax.swing.JTextField jtxtClass;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtSem1;
    private javax.swing.JTextField jtxtSem2;
    private javax.swing.JTextField jtxtSem3;
    private javax.swing.JLabel lblSemj3;
    // End of variables declaration//GEN-END:variables
}
